spring:
  profiles: dev

server:
  port: 0
  
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    initialInstanceInfoReplicationIntervalSeconds: 5
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    leaseRenewalIntervalInSeconds: 30
    leaseExpirationDurationInSeconds: 90
    preferIpAddress: true

    
logging:
  level:
    ROOT: INFO
    org.springframework.web: DEBUG
    org.springframework.web.cors: DEBUG
  file: ./Logs/${spring.application.name}.log

mongo:
  db:
    user: test
    password: test
    host: 172.26.115.75
    port: 27017
    database: test
 
---
spring:
  profiles: docker
 
server:
  port: 0
 
eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://192.168.99.100:8761/eureka/ 
mongo:
  db:
    user: test
    password: test
    host: 192.168.99.100
    port: 27017
    database: test 

---
spring:
  profiles: dev

server:
  port: 0

eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
mongo:
  db:
    user: test
    password: test
    host: 172.26.116.75
    port: 27017
    database: test

---
spring:
  profiles: vagrant

server:
  port: 0

eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
mongo:
  db:
    user: test
    password: test
    host: localhost
    port: 27017
    database: test

    