spring:
    profiles: docker
    jpa:
        database: MYSQL

    datasource:
        url: jdbc:mysql://localhost:3306/library
        username: root
        password: toor
server:
  port: 0

flyway:
    baselineOnMigrate: true

eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/


---

spring:
    profiles: dev
    jpa:
        database: MYSQL

    datasource:
        url: jdbc:mysql://172.26.116.75:3306/library
        username: fsegroup
        password: fsegroup
        driver: com.mysql.jdbc.Driver
server:
  port: 0

flyway:
    baselineOnMigrate: true

eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/


