spring:
  profiles: dev1

server:
  port: 0
  
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    initialInstanceInfoReplicationIntervalSeconds: 5
    serviceUrl:
      defaultZone: http://192.168.99.100:8761/eureka/
  instance:
    instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    leaseRenewalIntervalInSeconds: 30
    leaseExpirationDurationInSeconds: 90
    preferIpAddress: true

    
logging:
  level:
    ROOT: DEBUG
    org.springframework.web: DEBUG
    org.springframework.web.cors: DEBUG
  file: ./Logs/${spring.application.name}.log

mongo:
  db:
    user: test
    password: test
    host: 172.26.115.75
    port: 27017
    database: test 
---
spring:
  profiles: docker
 
server:
  port: 0
 
eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://192.168.99.100:8761/eureka/ 
mongo:
  db:
    user: test
    password: test
    host: 192.168.99.100
    port: 27017
    database: test 

---
spring:
    profiles: dev
    jpa:
        database: MYSQL
        lower_case_table_names: 0

    datasource:
        url: jdbc:mysql://localhost:3306/library
        username: root
        password: toor
server:
  port: 0

flyway:
    baselineOnMigrate: true

eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

---
spring:
    profiles: vagrant
    jpa:
        database: MYSQL

    datasource:
        url: jdbc:mysql://localhost:3306/library
        username: fsegroup
        password: fsegroup
server:
  port: 0

#flyway:
#    baselineOnMigrate: true

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    initialInstanceInfoReplicationIntervalSeconds: 5
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/
  instance:
    instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    leaseRenewalIntervalInSeconds: 30
    leaseExpirationDurationInSeconds: 90
    preferIpAddress: true


