version: '2'
services:
  user-service:
    image: user-1.0
    depends_on:
     - discovery-service
    image: library-1.0
    depends_on:
     - discovery-service
     - mongo-service
  discovery-service:
    image: registry-1.0
    ports:
     - "8761:8761"
  gateway-service:
    image: gateway-1.0
    depends_on:
     - discovery-service
    ports:
     - "8765:8765"
  mongo-service:
    image: mongo
    ports: 
     - "27017:27017"
  library-admin-ui:
    image: naveen/library-admin-ui
    ports:
     - "4200:4200"
    depends_on:
     - gateway-service

