spring:
  profile: dev1
server:
  port: 8765
  server-header: Web
  error:
    whitelabel:
      enabled: false
  
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    initialInstanceInfoReplicationIntervalSeconds: 40
    serviceUrl:
      defaultZone: http://192.168.99.100:8761/eureka/
  instance:
    instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    leaseRenewalIntervalInSeconds: 30
    leaseExpirationDurationInSeconds: 90
    preferIpAddress: true

ribbon:
    ServerListRefreshInterval: 1000  
    ReadTimeout: 60000
    ConnectTimeout: 60000
    OkToRetryOnAllOperations: false  

zuul:
  health:
    enabled: false
  ignoredServices: "*"
  routes:
    libraryservice:
      path: /fse/**
    
hystrix:
  command:
    default:
      execution.timeout.enabled: false
      
      
logging:
  level:
    ROOT: INFO
    org.springframework.web: INFO
    com.ctc.ctfs.dss.gatewayservice.filters: DEBUG
  file: D:/Ness/FullStack/POC/Logs/${spring.application.name}.log
    
management:
  add-application-context-header: false

gatewayserver:
  cors:
    origins: http://192.168.99.100:4502
    methods: OPTIONS,POST
    allow-credentials: true
    allow-header: all
    
---

spring:
  profiles: docker
 
server:
  port: 8765
 
zuul:
  health:
    enabled: false
  ignoredServices: "*"
  routes:
    libraryservice:
      path: /fse/**
 
eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://192.168.99.100:8761/eureka/
---
spring:
  profiles: dev

server:
  port: 8765

zuul:
  health:
    enabled: false
  ignoredServices: "*"
  routes:
    libraryservice:
      path: /fse/**
    userservice:
      path: /user/**

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    initialInstanceInfoReplicationIntervalSeconds: 40
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/
  instance:
    instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    leaseRenewalIntervalInSeconds: 30
    leaseExpirationDurationInSeconds: 90
    preferIpAddress: true
