server:
  port: 8761

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
  server:
    enable-self-preservation: false
    waitTimeInMsWhenSyncEmpty: 0

logging:
  level:
    com.netflix.discovery.DiscoveryClient: TRACE
  file: D:/Ness/FullStack/POC/Logs/${spring.application.name}.log

---
spring:
  profiles: docker
 
server:
  port: 8761
 
eureka:
  instance:
    hostname: discovery
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
       #defaultZone: http://user:${eureka.password}@discovery2:8762/eureka/


---
spring:
  profiles: dev

server:
  port: 8761

eureka:
  instance:
    hostname: discovery
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
       #defaultZone: http://user:${eureka.password}@discovery2:8762/eureka/
logging:
  level:
    com.netflix.discovery.DiscoveryClient: TRACE
  file: ./Logs/${spring.application.name}.log
       