server:
  port: 8761

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
  server:
    enable-self-preservation: false
    waitTimeInMsWhenSyncEmpty: 0

logging:
  level:
    com.netflix.discovery.DiscoveryClient: TRACE
  file: ./logs/${spring.application.name}.log

---
spring:
  profiles: local

eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/     
      
---
spring:
  profiles: dev

eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/

---
spring:
  profiles: docker
 
eureka:
  instance:
    hostname: discovery
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/