server:
  port: 9090
  
security:
  oauth2: 
    resource:
      id: id
      
logging:
  level:
    ROOT: INFO
    org.springframework.web: INFO
    com.ctc.ctfs.dss.gatewayservice.filters: DEBUG
  file: ./logs/${spring.application.name}.log
  
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    initialInstanceInfoReplicationIntervalSeconds: 40  
  instance:
    instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    leaseRenewalIntervalInSeconds: 30
    leaseExpirationDurationInSeconds: 90
    preferIpAddress: true  
        
---  
spring:
  profiles: local
  ### H2 Database Settings
  datasource:
    url: jdbc:h2:mem:auth-server;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    platform: h2
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true
        
### H2 Settings
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false

eureka:  
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/         
---  
spring:
  profiles: dev
  jpa:
    database: MYSQL
    show-sql: true
    hibernate:
      #ddl-auto: update      
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties: 
      hibernate: 
        show-sql: true
        use_sql_comments: true
        format_sql: true
        dialect: org.hibernate.dialect.MySQL5Dialect
  datasource:
      driver: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/library
      username: fsegroup
      password: fsegroup
      testWhileIdle: true
      validationQuery: SELECT 1

eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/   
      
---  
spring:
  profiles: docker
  jpa:
      database: MYSQL
  datasource:
      driver: com.mysql.jdbc.Driver
      url: jdbc:mysql://192.168.99.100:3306/library
      username: fsegroup
      password: fsegroup

eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.99.100:8761/eureka/          
